name: four_deals_shopping
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  awesome_dropdown: ^0.0.4
  country_code_picker: ^2.0.2

  pin_code_fields: ^7.4.0
  carousel_slider: ^4.1.1
  stylish_bottom_bar: ^0.1.3
  floating_bottom_bar: ^0.0.1
  bottom_sheet: ^3.0.0
  syncfusion_flutter_sliders: ^20.1.61
  image_picker: ^0.8.4+1
  flutter_rating_bar: ^4.0.1
  animated_radio_buttons: ^1.0.0
  custom_radio_grouped_button: ^2.1.2
  share: ^2.0.4
  flutter_phone_direct_caller: ^2.1.1
  shared_preferences: ^2.0.7
  cupertino_progress_bar: ^0.2.0
  http: ^0.13.4
  stacked: ^2.2.8
  firebase_messaging: ^11.1.0
  firebase_core: ^1.10.0
  firebase_auth: ^3.3.5
  rating_bar: ^0.2.0
  dropdown_below: ^1.0.3
  path_provider: ^2.0.11
  firebase_storage: ^10.1.0
  cloud_firestore: ^3.1.0
  firebase_database: ^8.1.0

  flutter_inappwebview: ^5.4.3+7
  flutter_facebook_login:
  google_sign_in: ^5.4.0
  flutter_local_notifications: ^9.1.5
  change_app_package_name: ^1.1.0
  toast: ^0.1.5
  record: ^3.0.2
  path: ^1.8.0
  just_audio: ^0.9.18
  audioplayers: ^0.20.1
  seekbar: ^0.0.2
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
